### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by cfoellmann** [ReGlot/ReGlot#1]
Hi guys,

where is the GlotPress for GlotPress?
I would really like to translate the interface into German.

**Comment by fmestrone** [comment]
Hi there,

I am just writing my own hack of GlotPress to use it with Elgg, I am not really aware of how the GlotPress product is translated or whether the GlotPress guys are doing it at all. I am interested in that feature too, though, and am thinking of writing an import tool for gettext files for GlotPress similar to what I'm doing for PHP. I don't have a timescale yet, though.

Are you a PHP developer? Do you know anything about WordPress plugins? If so and if you have time to help, I can definitely give you some pointers to get started and maybe we could get it done more quickly as a joint effort.

Federico

**Comment by cfoellmann** [comment]
I was under the impression that this is some official mirror. At least I hoped because I hate subversion.

Are you syncing new commits from svn to git? That would be great.
Joining forces sounds good but I am no great PHP coder.

**Comment by fmestrone** [comment]
Oh no, not at all. If I gave that impression I am sorry and rectify. This is a copy of GlotPress with some significant alterations to the one you find on subversion (I do update from svn, by the way).
Main differences at the moment, apart from the Elgg stuff:
- installation wizard (you create the database first, drop the files into the document root, then browse to the website which will do the rest)
- simple user management (add, delete, make admin)
- ability to cleanly delete projects and translation sets, which will delete everything relating to the them in database
- ability to browse by project, but also by translation language

**Comment by cfoellmann** [comment]
I think your post on blog.glotpress.org lead me on the way here and my misunderstanding of the nature of this repo.

It is nice that you import the subversion changes to this repo so I will definitely keep using your version, GitHub rulez :-)
My only concern is that it is not really possible to commit the changes back to the main project easily. Any thoughts on that?
The only way to do it I see is generating patches and committing them to the SVN.

EDIT:
(ADD) I have my modified version here: http://translate.foe-services.de if you are interested. I changed some coding beside the interface and will make a fork with these changes.

**Comment by cfoellmann** [comment]
One thing more:

Is the svn2github sync automated? If not I am currently looking into automating synchronization of some svn repos to github and could add the glotpress to my configuration

**Comment by fmestrone** [comment]
No, it is not automated. There doesn't seem to be much activity at the moment anyway, so I'll stick to doing it manually for the time being... I use Cornerstone for SVN, which notifies me when there are updates on the repository.

**Comment by fmestrone** [comment]
Re your previous post...

Yes, I think the only way is to create patches from github and submit them in your tickets for GlotPress... Then hope that someone will actually import them into the code ;-)

**Comment by cfoellmann** [comment]
my auto-sync mirror is up and running @ https://github.com/foe-services-mirrors/GlotPress-mirror and is updated once every hour

**Comment by fmestrone** [comment]
Hey, that's great! I'm going to add that as an upstream remote to my repo :-)) Out of curiosity, how do you set up a mirror like that? Is it difficult? It might be useful for me in the future, although the only case where I need it right now is GlotPress and that's solved, thanks to you ;-)

**Comment by cfoellmann** [comment]
I looked for a guide and found this: http://oddthesis.org/posts/2008-08-mirroring-svn-repository-to-github/
Worked like a charm :-)

My dev machine has enough free resources. If you like to mirror another svn just tell me.

**Comment by baden03** [comment]
Just installed the _official_ GlotPress, and was surprised that it did not have many of the features this fork seems include.  I will install this version and if it 'does what it says on the tin' we would be happy to fork it and start adding the Gettext Calls.

**Comment by fmestrone** [comment]
@baden03 Great, I'm still smoothing out some bits and pieces, but do contact me if you have issues with installation or anything else. If you could help with the gettext bits, that would be great.

I have also added another feature in the meantime, which is browsing translations by user...

**Comment by baden03** [comment]
Just a quick note that I have made some corrections and have gotten the translation files to load correctly.  I have send a pull request if you wish to check out the changes.  In the meantime, here is a link to the GlotPress/RePress translation project: http://translate.twinpictures.de/projects/glotpress
German (de_DE) Translation is  underway.

It is worth noting that there are MANY translations related only to backpress... it might be wise to edit the .pot file to only inclue files related specifically to GlotPress.

**Comment by cfoellmann** [comment]
How about splitting it up and providing a backpress translation in the process + the GlotPress translation as a subproject? Or the other way around.

**Comment by cfoellmann** [comment]
I have some more suggestions:
- lets stick with ReGlot, add a contributors list to the README file in the repo and not add everyone to the footer. Or it will look like this: http://picload.org/view/dlricrp/glotpress_footer.gif.html soon
- close the wiki and issues in your forks

**Comment by baden03** [comment]
Contributors have been moved from the footer, and the footer has also been removed from the translation files.
Wiki and issues in my fork have been closed.
Does the pull request pull from that specific commit, or do I need to re-issue a pull request so you merge with the latest version?

**Comment by cfoellmann** [comment]
Your last changes you describe are not in the pull request because the commit is not included

**Comment by baden03** [comment]
Changes have now been commited

**Comment by fmestrone** [comment]
@cfoellmann @baden03 

Thanks so much for your contribution. Apologies for not having looked at your pull requests yet. Right now I am about to set up a website for ReGlot and another product based on it... on top of that I have to earn a living, too ;-)

I will look at your pull requests as soon as I have completed phase one of my plan, and then we can discuss where to go from here. Theming and internationalization are things I want to do as well, so it's great that I have some support in this... we will get started soon, just give me a little time.

**Comment by cfoellmann** [comment]
@baden03 I looked through your pull request and at your reglot installation.
How did you get it to accept the German .po/.mo files? Simple dropin is not working for me.

About the pull request: you should use the version control for what its for. Revert the commits you reversed with git!

**Comment by baden03** [comment]
This is over two years old.  I have since switched back to the official GlotPress as it is actively developed.
https://glotpress.trac.wordpress.org/timeline
