### ISSUE TITLE
Transfer to Org:ReGlot was bad

### ISSUE THREAD

**Issue by cfoellmann** [ReGlot/ReGlot#13]
Hi Federico,

is it possible that you just created a new repo of ReGlot in the ReGlot Org?

This way no pull request and issue content is transfered.
You should transfer the complete repo via the Admin panel to the Org. This way forks, pull request, et cetera will stay active

**Comment by fmestrone** [comment]
Happy now? ;-) I wish you had told me earlier about transferring... LOL I'm not very good at github, I spent a long time moving the repositories manually :-(

Welcome to the new home of ReGlot

**Comment by cfoellmann** [comment]
I hope my post was not insulting. Sorry if it was.

All perfect now. If you need/want any help on the website or GitHub do not hesitate to ask.
My Email-address is on here: https://github.com/cfoellmann
Just send me a mail. Send me a Skype/Trillian Astra/ICQ or Facebook Chat Username and we can chat. Trillian rulez ;-)

**Comment by cfoellmann** [comment]
One last tip:
Your should add yourself as a publicly visible member auf the org.
