### ISSUE TITLE
Howto

### ISSUE THREAD

**Issue by cfoellmann** [ReGlot/ReGlot#2]
Hi guys,

I dont know if I am too stupid or something is wrong.
I tried to import the first Project:

https://wordpress.org/extend/plugins/black-studio-tinymce-widget/ to translate it into German.
https://plugins.trac.wordpress.org/browser/black-studio-tinymce-widget/trunk/languages are the files I want to import.

Nothing is working. My GlotPress import does show this: http://picload.org/view/docgigp/glotpress_import.jpg.html

????

**Comment by fmestrone** [comment]
Hi there! No, not your fault, totally mine! I have updated the language pack format so the plugin currently online does not work with ReGlot anymore (I have renamed it ;-) to avoid confusion). I will update tomorrow, let me do some finally checks and tests first... Sorry, my mistake!

**Comment by fmestrone** [comment]
Oh, hold on! Sorry again, I got you wrong. I thought you were importing an Elgg language pack! I'll have a look, but I don't know much about po/mo etc... I'll keep you posted...

**Comment by fmestrone** [comment]
It worked for me! Here's what I did:
- created new project for TinyMCE
- Imported originals from .pot file
- Created translation set for Spanish
- Imported translations from ES .po file
- Created translation set for Italian
- Imported translations from IT .po file
  and it did what I expected, no funny screens anywhere... not sure what happened there, did u get any error messages anywhere? could it be an issue with the UI customization you have set up?

**Comment by cfoellmann** [comment]
Where do I "Imported originals from .pot file" this?
There is no option for .pot files. Or is there?

**Comment by fmestrone** [comment]
.pot files are just .po files that contain the original strings, so you use the .po format ;-)

**Comment by cfoellmann** [comment]
I knew about the pot file but... I may be too stupid.

Did all the steps you described above. 
On the project page : http://translate.foe-services.de/projects/black-studio-tinymce-widget 
"There are no translations of this project." is displayed.

How do I activate the translations?
I used the latest checkout of ReGlot :-) (Like the name. You should adjust the README too.)

**Comment by fmestrone** [comment]
Strange... it should all work fine... As it's very early stages, and I have only been able to try it myself on my own servers, I'm quite keen to find out what is going on. I have registered on your site (fmestrone). Could you make me an admin temporarily so I can have a better look? Whatever I do, the project deletion feature I added is quite powerful and thorough, so you can reset whenever you want without leaving any trace of my passage ;-)

**Comment by cfoellmann** [comment]
I made you an admin. Feel free to do anything to the install.
I can make an ftp account if you like.

**Comment by fmestrone** [comment]
Thanks. It is a problem of clarity. By default, the option for recursive translation sets is on, which only created projects in subprojects. Now I have made a change to the repository that should make the interface a lot clearer. Also, if a project does not have a subproject, now it creates the translation set in the project itself... Hope it makes sense.

I have done your Spanish, do you want to try with the Italian to see if it is better now? Don't forget to pull new changes... ;-)

**Comment by cfoellmann** [comment]
Thanks for the help.
I made one major mistake. It was still not working until I realized that the option "Recursively create sets in subprojects" needs to be deactivated.

Would be a deactivated state on load ok? I do not really understand the meaning of this option and why it does not work when checked.
