### ISSUE TITLE
url-slag duplicate in url

### ISSUE THREAD

**Issue by cfoellmann** [ReGlot/ReGlot#5]
In my installation the translation site generates a duplicate of the language slag at the end (https://translate.foe-services.de/projects/black-studio-tinymce-widget/de/de)

Does anyone have the same "problem"?

**Comment by fmestrone** [comment]
Hi, it is not a duplicate! the first one is the translation set, the second one is the language ;-) normally a set has the same slug as the language, but that doesn't have to be the case - you could for example offer an official german translation and then one with a humorous tone (https://translate.foe-services.de/projects/black-studio-tinymce-widget/funnyde/de), or maybe polite german (https://translate.foe-services.de/projects/black-studio-tinymce-widget/sie-de/de) and conversational german (https://translate.foe-services.de/projects/black-studio-tinymce-widget/du-de/de). in such cases, the language slug doesn't change, but the translation set does...

Please, do not say 'slag', it's a slug (LOL) slag is a rude word ;-)

**Comment by cfoellmann** [comment]
Ok thanks for making that clear.
