### ISSUE TITLE
Language per user

### ISSUE THREAD

**Issue by cfoellmann** [ReGlot/ReGlot#6]
Would be nice for the user to choose the language of the interface

**Comment by baden03** [comment]
This is added as a TODO.  However, in the meantime, there is a quick fix to have the interface language automatically change based on the BROWSER's language settings.  I use this trick to test the .mo files after I upload them.
All you have to do is replace `define('GP_LANG', 'en_EN');` the following to your gp-config.php file:

```
$lang = substr(strtoupper(getenv("HTTP_ACCEPT_LANGUAGE")), 0, 2);
if($lang == "DE"){
    define ('GP_LANG', 'de_DE');
}
else{
    define('GP_LANG', '');
}
```

**Comment by fmestrone** [comment]
Sounds like a good idea, I haven't started work on an i18n'ed version of ReGlot yet, but it is something i will want to do. @baden03 I wouldn't want to change the config file, as i think that should allow for the site admin to make some choice  for the language that should be available regardless of browser setting. i will add that code to the bootstrap phase, if that makes sense to you...

**Comment by baden03** [comment]
I agree, this is only a temp solution for being able to switch between languages using the browser's language setting.  Ideally there should be a default language set in the config file and then the ability for each user to select their own language from one of the available translations in the user profile.
