### ISSUE TITLE
Organizing the project

### ISSUE THREAD

**Issue by cfoellmann** [ReGlot/ReGlot#7]
I know it would be another rename but it would look right to me if the project is reachable under https://github.com/ReGlot/ReGlot

What do you think?

**Comment by fmestrone** [comment]
i didn't get what you meant initially, now i see ;-) good idea! done it! i will complete the switch over the next few days...

**Comment by cfoellmann** [comment]
@fmestrone How is your progress concerning the targets you want to meet with ReGlot?
When are you free to have a look at the pull requests?
I am eager to do some more work for the project :-)

**Comment by fmestrone** [comment]
Hi Christian,

I have an issue with bulk actions at the moment which I think has priority (it is mentioned in one of the issues too).

I have seen you have added me to Skype, maybe we can have a chat when you're online and decide how to move forward.

Fed

**Comment by cfoellmann** [comment]
I am missing the commits from the original GlotPress project.
There is not much activity but dont we get an import problem in the future?

Now the project is still young. What do you think? Any problems foreseeable in the future?

**Comment by fmestrone** [comment]
Hi there

Not sure what u mean. I have simply moved the repository over to the organisation. It should all be there...

**Comment by cfoellmann** [comment]
The git history is missing from the original GlotPress is missing.
After I fixed my mirror I found the official Mirror: https://github.com/buddypress/glotpress
Should be the upstream for ReGlot
