### ISSUE TITLE
License of GlotPress -> ReGlot

### ISSUE THREAD

**Issue by cfoellmann** [ReGlot/ReGlot#8]
Hi guys,

what is the license of GlotPress? This should still be current: https://glotpress.trac.wordpress.org/changeset/373 . Or not?

So ReGlot is GPLv2.
Right?

If yes, a LICENSE file should be added to the repo.

**Comment by baden03** [comment]
Did you not see this?: https://github.com/fmestrone/ReGlot/blob/master/license.txt

**Comment by cfoellmann** [comment]
I did not. :-(
Must be blind
